import "./globals.css";
import React, { ReactNode } from "react";
import type { Metadata } from "next";
import ReactQuery from "@/config/ReactQuery";
interface NextAuthProps {
  children: ReactNode;
  
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: NextAuthProps) {
  return (
    <html lang="en">
      <body className={"px-5 w-screen h-screen overflow-hidden"}>
        <ReactQuery>{children}</ReactQuery>
      </body>
    </html>
  );
}
